http:
  routers:
    app:
      rule: PathPrefix(`/v1/`) && host(`mygoogle.com`)
      service: app
      middlewares:
        - talsec-plugin
        - strip

    app2:
      rule: host(`mygoogle.com`)
      service: app
      middlewares:
        - strip

  services:
    app:
      loadBalancer:
        servers:
          - url: http://web

  middlewares:
    strip:
      stripPrefix:
        prefixes:
          - /v1/self-onboarding/complete
          - /v1/devices/self
        forceSlash: false

    talsec-plugin:
      plugin:
        talsec: {}
